### ISSUE TITLE
Migrate Windows packages or patch repodata for 1.0.1 builds

### ISSUE THREAD

**Issue by carterbox** [conda-forge/libavif-feedstock#33]
Just for completeness: I noticed this in particular on Windows as the pinned libavif==1.0.1 actually adds a run_exports on `libavif==1.0.1`, not `libavif16` (see https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fwin-64%2Flibavif-1.0.1-h7a9aacb_3.conda, issue fixed in https://github.com/conda-forge/libavif-feedstock/pull/25), so beside the pinning update all packages that depends on libavif and have Windows builds need to be rebuilt (or the repodata info patched).

_Originally posted by @traversaro in https://github.com/conda-forge/libavif-feedstock/issues/32#issuecomment-2132358001_

**Comment by traversaro** [comment]
Repos (https://github.com/search?q=org%3Aconda-forge+%22-+libavif%22+language%3AYAML&type=code):
* `sdl2_image` : https://github.com/conda-forge/sdl2_image-feedstock/pull/35 
* `tensorstore` : non needed, does not supports windows
* `imagecodecs`:  https://github.com/conda-forge/imagecodecs-feedstock/pull/105
* `libheif` : https://github.com/conda-forge/libheif-feedstock/pull/22

**Comment by hmaarrfk** [comment]
thanks would rather not take too heavy of a hand in these feedstocks if not needed, but let me know if you think i should.

**Comment by traversaro** [comment]
All PR closed, I think we can close the issue.

**Comment by traversaro** [comment]
> `tensorstore` : non needed, does not supports windows

Anyhow, this was re-rendered as part of the package update in https://github.com/conda-forge/tensorstore-feedstock/pull/33 .
